name: local_config
description: |
  Make changes to your app's default behavior 
  and appearance by changing parameter values 
  — just like Firebase Remote Config, but locally.
version: 0.2.3
topics:
  - local
  - config
  - management
  - persistence
  - storage
repository: https://github.com/adrianotelesc/local_config
issue_tracker: https://github.com/adrianotelesc/local_config/issues

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.3.4
  flutter_secure_storage: ^9.2.2
  re_editor: ^0.8.0
  re_highlight: ^0.0.3
  get_it: ^7.6.7
  provider: ^6.1.2
  boxy: ^2.2.2
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  generate: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans/GoogleSans-VariableFont_GRAD,opsz,wght.ttf
        - asset: assets/fonts/GoogleSans/GoogleSans-Italic-VariableFont_GRAD,opsz,wght.ttf
          style: italic
    - family: GoogleSansCode
      fonts:
        - asset: assets/fonts/GoogleSansCode/GoogleSansCode-VariableFont_wght.ttf
        - asset: assets/fonts/GoogleSansCode/GoogleSansCode-Italic-VariableFont_wght.ttf
          style: italic
